# docker-compose.grpc-server.yml
version: '3.8'

services:
  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    container_name: grpc-server
    ports:
      - "50051:50051"
    networks:
      - app-network

networks:
  app-network:
    external: false