version: '3.8'

networks:
  app-network:
    external: false

services:
  redis-template: &redis_base
    image: bitnami/redis:7.4.0
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    volumes:
      - ./redis.conf:/bitnami/redis/conf/redis.conf  # Monta el archivo de configuración

  redis1:
    <<: *redis_base
    container_name: redis-server-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data_1:/bitnami/redis/data

  redis2:
    <<: *redis_base
    container_name: redis-server-2
    ports:
      - "6380:6379"
    volumes:
      - redis_data_2:/bitnami/redis/data

  redis3:
    <<: *redis_base
    container_name: redis-server-3
    ports:
      - "6381:6379"
    volumes:
      - redis_data_3:/bitnami/redis/data

  redis4:
    <<: *redis_base
    container_name: redis-server-4
    ports:
      - "6382:6379"
    volumes:
      - redis_data_4:/bitnami/redis/data

  redis5:
    <<: *redis_base
    container_name: redis-server-5
    ports:
      - "6383:6379"
    volumes:
      - redis_data_5:/bitnami/redis/data

  redis6:
    <<: *redis_base
    container_name: redis-server-6
    ports:
      - "6384:6379"
    volumes:
      - redis_data_6:/bitnami/redis/data

  redis7:
    <<: *redis_base
    container_name: redis-server-7
    ports:
      - "6385:6379"
    volumes:
      - redis_data_7:/bitnami/redis/data

  redis8:
    <<: *redis_base
    container_name: redis-server-8
    ports:
      - "6386:6379"
    volumes:
      - redis_data_8:/bitnami/redis/data
  
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redis-insight
    volumes: 
      - redis-insight:/data
    ports:
      - "5540:5540" 
    networks: 
      - app-network
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8

volumes:
  redis_data_1:
    driver: local
  redis_data_2:
    driver: local
  redis_data_3:
    driver: local
  redis_data_4:
    driver: local
  redis_data_5:
    driver: local
  redis_data_6:
    driver: local
  redis_data_7:
    driver: local
  redis_data_8:
    driver: local
  redis-insight:
